# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

keymap = [
	{ on = "<Esc>", run = "escape", desc = "退出可视模式，取消选择，或退出搜索" },
	{ on = "<C-[>", run = "escape", desc = "退出可视模式，取消选择，或退出搜索" },
	{ on = "q",     run = "quit",   desc = "退出程序" },
	{ on = "Q",     run = "quit --no-cwd-file", desc = "退出程序（不保存当前目录文件）" },
	{ on = "<C-c>", run = "close",  desc = "关闭当前标签页（如果是最后一个则退出）" },
	{ on = "<C-z>", run = "suspend", desc = "挂起程序（发送到后台）" },

	# 光标移动
	{ on = "k", run = "arrow prev", desc = "光标上移一个文件" },
	{ on = "j", run = "arrow next", desc = "光标下移一个文件" },

	{ on = "<Up>",   run = "arrow prev", desc = "光标上移一个文件" },
	{ on = "<Down>", run = "arrow next", desc = "光标下移一个文件" },

	{ on = "<C-u>", run = "arrow -50%", desc = "光标上移半页" },
	{ on = "<C-d>", run = "arrow 50%",  desc = "光标下移半页" },
	{ on = "<C-b>", run = "arrow -100%", desc = "光标上移一整页" },
	{ on = "<C-f>", run = "arrow 100%",  desc = "光标下移一整页" },

	{ on = "<S-PageUp>",   run = "arrow -50%", desc = "光标上移半页" },
	{ on = "<S-PageDown>", run = "arrow 50%",  desc = "光标下移半页" },
	{ on = "<PageUp>",     run = "arrow -100%", desc = "光标上移一整页" },
	{ on = "<PageDown>",   run = "arrow 100%",  desc = "光标下移一整页" },

	{ on = [ "g", "g" ], run = "arrow top", desc = "跳转到列表顶部" },
	{ on = "G",          run = "arrow bot", desc = "跳转到列表底部" },

	# 目录导航
	{ on = "h", run = "leave", desc = "返回上一级目录" },
	{ on = "l", run = "enter", desc = "进入下一级目录（光标所在目录）" },

	{ on = "<Left>",  run = "leave", desc = "返回上一级目录" },
	{ on = "<Right>", run = "enter", desc = "进入下一级目录（光标所在目录）" },

	{ on = "H", run = "back",    desc = "返回上一个浏览过的目录" },
	{ on = "L", run = "forward", desc = "前进到下一个浏览过的目录" },

	# 选择
	{ on = "<Space>", run = [ "toggle", "arrow next" ], desc = "切换当前文件的选中状态并移动到下一个文件" },
	{ on = "<C-a>",   run = "toggle_all --state=on",    desc = "全选所有文件" },
	{ on = "<C-r>",   run = "toggle_all",               desc = "反选所有文件" },

	# 可视模式
	{ on = "v", run = "visual_mode",         desc = "进入可视模式（框选模式）" },
	{ on = "V", run = "visual_mode --unset", desc = "进入可视取消模式（取消框选）" },

	# 预览面板滚动
	{ on = "K", run = "arrow top", desc = "预览面板快速上移5行" },
	{ on = "J", run = "arrow bot", desc = "预览面板快速下移5行" },

	# 定位（Spot）
	{ on = "<Tab>", run = "spot", desc = "显示光标所在文件信息" },

	# 文件操作
	{ on = "o",         run = "open",                        desc = "打开选中的文件或目录" },
	{ on = "O",         run = "open --interactive",          desc = "交互式打开选中的文件或目录" },
	{ on = "<Enter>",   run = "open",                        desc = "打开选中的文件或目录" },
	{ on = "<S-Enter>", run = "open --interactive",          desc = "交互式打开选中的文件或目录" },
	{ on = "y",         run = "yank",                        desc = "复制选中的文件" },
	{ on = "x",         run = "yank --cut",                  desc = "剪切选中的文件" },
	{ on = "p",         run = "paste",                       desc = "粘贴复制/剪切的文件" },
	{ on = "P",         run = "paste --force",               desc = "强制粘贴（覆盖同名文件）" },
	{ on = "-",         run = "link",                        desc = "创建复制文件的绝对路径符号链接" },
	{ on = "_",         run = "link --relative",             desc = "创建复制文件的相对路径符号链接" },
	{ on = "<C-->",     run = "hardlink",                    desc = "创建硬链接" },
	{ on = "Y",         run = "unyank",                      desc = "取消复制状态" },
	{ on = "X",         run = "unyank",                      desc = "取消剪切状态" },
	{ on = "d",         run = "remove",                      desc = "将选中文件移动到回收站" },
	{ on = "D",         run = "remove --permanently",        desc = "永久删除选中的文件" },
	{ on = "a",         run = "create",                      desc = "创建新文件（以/结尾表示目录）" },
	{ on = "r",         run = "rename --cursor=before_ext",  desc = "重命名选中的文件（光标停在扩展名前）" },
	{ on = ";",         run = "shell --interactive",         desc = "打开一个交互式 Shell 执行命令" },
	{ on = ":",         run = "shell --block --interactive", desc = "打开一个交互式 Shell，等待命令执行完成" },
	{ on = ".",         run = "hidden toggle",               desc = "显示/隐藏隐藏文件" },
	{ on = "s",         run = "search --via=fd",             desc = "使用 fd 按名称搜索文件" },
	{ on = "S",         run = "search --via=rg",             desc = "使用 ripgrep 按内容搜索文件" },
	{ on = "<C-s>",     run = "escape --search",             desc = "取消当前搜索" },
	{ on = "z",         run = "plugin fzf",                  desc = "通过 fzf 快速跳转到文件或目录" },
	{ on = "Z",         run = "plugin zoxide",               desc = "通过 zoxide 快速跳转目录" },

	# 行模式显示
	{ on = [ "m", "s" ], run = "linemode size",        desc = "显示文件大小模式" },
	{ on = [ "m", "p" ], run = "linemode permissions", desc = "显示文件权限模式" },
	{ on = [ "m", "b" ], run = "linemode btime",       desc = "显示文件创建时间模式" },
	{ on = [ "m", "m" ], run = "linemode mtime",       desc = "显示文件修改时间模式" },
	{ on = [ "m", "o" ], run = "linemode owner",       desc = "显示文件所有者模式" },
	{ on = [ "m", "n" ], run = "linemode none",        desc = "关闭行信息显示" },

	# 复制信息
	{ on = [ "c", "c" ], run = "copy path",             desc = "复制文件完整路径" },
	{ on = [ "c", "d" ], run = "copy dirname",          desc = "复制文件所在目录路径" },
	{ on = [ "c", "f" ], run = "copy filename",         desc = "复制文件名（包含扩展名）" },
	{ on = [ "c", "n" ], run = "copy name_without_ext", desc = "复制文件名（不包含扩展名）" },

	# 文件过滤
	{ on = "f", run = "filter --smart", desc = "通过智能匹配快速过滤文件" },

	# 查找
	{ on = "/", run = "find --smart",            desc = "查找下一个匹配的文件" },
	{ on = "?", run = "find --previous --smart", desc = "查找上一个匹配的文件" },
	{ on = "n", run = "find_arrow",              desc = "跳转到下一个搜索结果" },
	{ on = "N", run = "find_arrow --previous",   desc = "跳转到上一个搜索结果" },

	# 排序
	{ on = [ ",", "m" ], run = [ "sort mtime --reverse=no", "linemode mtime" ], desc = "按修改时间排序（从旧到新）" },
	{ on = [ ",", "M" ], run = [ "sort mtime --reverse", "linemode mtime" ],    desc = "按修改时间排序（从新到旧）" },
	{ on = [ ",", "b" ], run = [ "sort btime --reverse=no", "linemode btime" ], desc = "按创建时间排序（从旧到新）" },
	{ on = [ ",", "B" ], run = [ "sort btime --reverse", "linemode btime" ],    desc = "按创建时间排序（从新到旧）" },
	{ on = [ ",", "e" ], run = "sort extension --reverse=no",                   desc = "按扩展名排序（正序）" },
	{ on = [ ",", "E" ], run = "sort extension --reverse",                      desc = "按扩展名排序（倒序）" },
	{ on = [ ",", "a" ], run = "sort alphabetical --reverse=no",                desc = "按字母排序（正序）" },
	{ on = [ ",", "A" ], run = "sort alphabetical --reverse",                   desc = "按字母排序（倒序）" },
	{ on = [ ",", "n" ], run = "sort natural --reverse=no",                     desc = "自然排序（正序）" },
	{ on = [ ",", "N" ], run = "sort natural --reverse",                        desc = "自然排序（倒序）" },
	{ on = [ ",", "s" ], run = [ "sort size --reverse=no", "linemode size" ],   desc = "按文件大小排序（从小到大）" },
	{ on = [ ",", "S" ], run = [ "sort size --reverse", "linemode size" ],      desc = "按文件大小排序（从大到小）" },
	{ on = [ ",", "r" ], run = "sort random --reverse=no",                      desc = "随机排序" },

	# 快速跳转目录
	{ on = [ "g", "h" ],       run = "cd ~",             desc = "跳转到用户主目录" },
	{ on = [ "g", "c" ],       run = "cd ~/.config",     desc = "跳转到 ~/.config 目录" },
	{ on = [ "g", "d" ],       run = "cd ~/Downloads",   desc = "跳转到 ~/Downloads 下载目录" },
	{ on = [ "g", "<Space>" ], run = "cd --interactive", desc = "交互式跳转到任意目录" },
	{ on = [ "g", "f" ],       run = "follow",           desc = "跟随光标所在的符号链接" },

	# 标签页
	{ on = "t", run = "tab_create --current", desc = "新建标签页（保持当前工作目录）" },

	{ on = "1", run = "tab_switch 0", desc = "切换到第一个标签页" },
	{ on = "2", run = "tab_switch 1", desc = "切换到第二个标签页" },
	{ on = "3", run = "tab_switch 2", desc = "切换到第三个标签页" },
	{ on = "4", run = "tab_switch 3", desc = "切换到第四个标签页" },
	{ on = "5", run = "tab_switch 4", desc = "切换到第五个标签页" },
	{ on = "6", run = "tab_switch 5", desc = "切换到第六个标签页" },
	{ on = "7", run = "tab_switch 6", desc = "切换到第七个标签页" },
	{ on = "8", run = "tab_switch 7", desc = "切换到第八个标签页" },
	{ on = "9", run = "tab_switch 8", desc = "切换到第九个标签页" },

	{ on = "[", run = "tab_switch -1 --relative", desc = "切换到上一个标签页" },
	{ on = "]", run = "tab_switch 1 --relative",  desc = "切换到下一个标签页" },

	{ on = "{", run = "tab_swap -1", desc = "当前标签页与前一个标签互换" },
	{ on = "}", run = "tab_swap 1",  desc = "当前标签页与后一个标签互换" },

	# 任务管理
	{ on = "w", run = "tasks:show", desc = "显示任务管理器（查看后台任务）" },

	# 帮助
	{ on = "~",    run = "help", desc = "打开帮助文档" },
	{ on = "<F1>", run = "help", desc = "打开帮助文档" },
]

[tasks]

keymap = [
	{ on = "<Esc>", run = "close", desc = "关闭任务管理器" },
	{ on = "<C-[>", run = "close", desc = "关闭任务管理器" },
	{ on = "<C-c>", run = "close", desc = "关闭任务管理器" },
	{ on = "w",     run = "close", desc = "关闭任务管理器" },

	{ on = "k", run = "arrow prev", desc = "光标上移到上一个任务" },
	{ on = "j", run = "arrow next", desc = "光标下移到下一个任务" },

	{ on = "<Up>",   run = "arrow prev", desc = "光标上移到上一个任务" },
	{ on = "<Down>", run = "arrow next", desc = "光标下移到下一个任务" },

	{ on = "<Enter>", run = "inspect", desc = "查看任务的详细信息" },
	{ on = "x",       run = "cancel",  desc = "取消当前选中的任务" },

	# 帮助
	{ on = "~",    run = "help", desc = "打开帮助文档" },
	{ on = "<F1>", run = "help", desc = "打开帮助文档" },
]

[spot]

keymap = [
	{ on = "<Esc>", run = "close", desc = "关闭 Spot 聚焦窗口" },
	{ on = "<C-[>", run = "close", desc = "关闭 Spot 聚焦窗口" },
	{ on = "<C-c>", run = "close", desc = "关闭 Spot 聚焦窗口" },
	{ on = "<Tab>", run = "close", desc = "关闭 Spot 聚焦窗口" },

	{ on = "k", run = "arrow prev", desc = "光标上移一行" },
	{ on = "j", run = "arrow next", desc = "光标下移一行" },
	{ on = "h", run = "swipe prev", desc = "切换到上一个文件" },
	{ on = "l", run = "swipe next", desc = "切换到下一个文件" },

	{ on = "<Up>",    run = "arrow prev", desc = "光标上移一行" },
	{ on = "<Down>",  run = "arrow next", desc = "光标下移一行" },
	{ on = "<Left>",  run = "swipe prev", desc = "切换到上一个文件" },
	{ on = "<Right>", run = "swipe next", desc = "切换到下一个文件" },

	# 复制
	{ on = [ "c", "c" ], run = "copy cell", desc = "复制当前选中的单元格内容" },

	# 帮助
	{ on = "~",    run = "help", desc = "打开帮助文档" },
	{ on = "<F1>", run = "help", desc = "打开帮助文档" },
]

[pick]

keymap = [
	{ on = "<Esc>",   run = "close",          desc = "取消选择并关闭窗口" },
	{ on = "<C-[>",   run = "close",          desc = "取消选择并关闭窗口" },
	{ on = "<C-c>",   run = "close",          desc = "取消选择并关闭窗口" },
	{ on = "<Enter>", run = "close --submit", desc = "确认选择并提交" },

	{ on = "k", run = "arrow prev", desc = "光标上移到上一个选项" },
	{ on = "j", run = "arrow next", desc = "光标下移到下一个选项" },

	{ on = "<Up>",   run = "arrow prev", desc = "光标上移到上一个选项" },
	{ on = "<Down>", run = "arrow next", desc = "光标下移到下一个选项" },

	# 帮助
	{ on = "~",    run = "help", desc = "打开帮助文档" },
	{ on = "<F1>", run = "help", desc = "打开帮助文档" },
]

[input]

keymap = [
	{ on = "<C-c>",   run = "close",          desc = "取消输入并关闭窗口" },
	{ on = "<Enter>", run = "close --submit", desc = "确认输入并提交" },
	{ on = "<Esc>",   run = "escape",         desc = "返回普通模式，或取消输入" },
	{ on = "<C-[>",   run = "escape",         desc = "返回普通模式，或取消输入" },

	# 模式切换
	{ on = "i", run = "insert",                          desc = "进入插入模式" },
	{ on = "I", run = [ "move first-char", "insert" ],   desc = "跳到行首第一个非空字符并进入插入模式" },
	{ on = "a", run = "insert --append",                 desc = "进入追加模式（光标后插入）" },
	{ on = "A", run = [ "move eol", "insert --append" ], desc = "跳到行尾并进入追加模式" },
	{ on = "v", run = "visual",                          desc = "进入可视模式（选择）" },
	{ on = "r", run = "replace",                         desc = "进入替换模式（替换一个字符）" },

	# 选择
	{ on = "V",     run = [ "move bol", "visual", "move eol" ], desc = "选择整行内容" },
	{ on = "<C-A>", run = [ "move eol", "visual", "move bol" ], desc = "从行尾选择到行首" },
	{ on = "<C-E>", run = [ "move bol", "visual", "move eol" ], desc = "从行首选择到行尾" },

	# 字符级移动
	{ on = "h",       run = "move -1", desc = "向左移动一个字符" },
	{ on = "l",       run = "move 1",  desc = "向右移动一个字符" },
	{ on = "<Left>",  run = "move -1", desc = "向左移动一个字符" },
	{ on = "<Right>", run = "move 1",  desc = "向右移动一个字符" },
	{ on = "<C-b>",   run = "move -1", desc = "向左移动一个字符" },
	{ on = "<C-f>",   run = "move 1",  desc = "向右移动一个字符" },

	# 单词级移动
	{ on = "b",         run = "backward",                    desc = "向左移动到当前或前一个单词的开头" },
	{ on = "B",         run = "backward --far",              desc = "向左移动到当前或前一个大写WORD的开头" },
	{ on = "w",         run = "forward",                     desc = "向右移动到下一个单词的开头" },
	{ on = "W",         run = "forward --far",               desc = "向右移动到下一个大写WORD的开头" },
	{ on = "e",         run = "forward --end-of-word",       desc = "向右移动到当前或下一个单词的结尾" },
	{ on = "E",         run = "forward --far --end-of-word", desc = "向右移动到当前或下一个大写WORD的结尾" },
	{ on = "<A-b>",     run = "backward",                    desc = "向左移动到单词开头" },
	{ on = "<A-f>",     run = "forward --end-of-word",       desc = "向右移动到单词结尾" },
	{ on = "<C-Left>",  run = "backward",                    desc = "向左移动到单词开头" },
	{ on = "<C-Right>", run = "forward --end-of-word",       desc = "向右移动到单词结尾" },

	# 行级移动
	{ on = "0",      run = "move bol",        desc = "跳到行首" },
	{ on = "$",      run = "move eol",        desc = "跳到行尾" },
	{ on = "_",      run = "move first-char", desc = "跳到行首第一个非空字符" },
	{ on = "^",      run = "move first-char", desc = "跳到行首第一个非空字符" },
	{ on = "<C-a>",  run = "move bol",        desc = "跳到行首" },
	{ on = "<C-e>",  run = "move eol",        desc = "跳到行尾" },
	{ on = "<Home>", run = "move bol",        desc = "跳到行首" },
	{ on = "<End>",  run = "move eol",        desc = "跳到行尾" },

	# 删除单个字符
	{ on = "<Backspace>", run = "backspace",         desc = "删除光标前的字符" },
	{ on = "<Delete>",    run = "backspace --under", desc = "删除光标下的字符" },
	{ on = "<C-h>",       run = "backspace",         desc = "删除光标前的字符" },
	{ on = "<C-d>",       run = "backspace --under", desc = "删除光标下的字符" },

	# 批量删除（kill）
	{ on = "<C-u>",         run = "kill bol",      desc = "删除光标到行首的内容" },
	{ on = "<C-k>",         run = "kill eol",      desc = "删除光标到行尾的内容" },
	{ on = "<C-w>",         run = "kill backward", desc = "删除光标到前一个单词开头" },
	{ on = "<A-d>",         run = "kill forward",  desc = "删除光标到下一个单词结尾" },
	{ on = "<C-Backspace>", run = "kill backward", desc = "删除光标到前一个单词开头" },
	{ on = "<C-Delete>",    run = "kill forward",  desc = "删除光标到下一个单词结尾" },

	# 剪切/复制/粘贴
	{ on = "d", run = "delete --cut",                                      desc = "剪切选择的内容" },
	{ on = "D", run = [ "delete --cut", "move eol" ],                      desc = "从当前光标剪切到行尾" },
	{ on = "c", run = "delete --cut --insert",                             desc = "剪切选择的内容并进入插入模式" },
	{ on = "C", run = [ "delete --cut --insert", "move eol" ],             desc = "从当前光标剪切到行尾并进入插入模式" },
	{ on = "s", run = [ "delete --cut --insert", "move 1" ],               desc = "剪切当前字符并进入插入模式" },
	{ on = "S", run = [ "move bol", "delete --cut --insert", "move eol" ], desc = "剪切整行并进入插入模式" },
	{ on = "x", run = [ "delete --cut", "move 1 --in-operating" ],         desc = "剪切当前字符" },
	{ on = "y", run = "yank",                                              desc = "复制选择的内容" },
	{ on = "p", run = "paste",                                             desc = "在光标后粘贴" },
	{ on = "P", run = "paste --before",                                    desc = "在光标前粘贴" },

	# 撤销/重做
	{ on = "u",     run = "undo", desc = "撤销上一步操作" },
	{ on = "<C-r>", run = "redo", desc = "重做上一步操作" },

	# 帮助
	{ on = "~",    run = "help", desc = "打开帮助文档" },
	{ on = "<F1>", run = "help", desc = "打开帮助文档" },
]

[confirm]

keymap = [
	{ on = "<Esc>",   run = "close",          desc = "取消确认并关闭窗口" },
	{ on = "<C-[>",   run = "close",          desc = "取消确认并关闭窗口" },
	{ on = "<C-c>",   run = "close",          desc = "取消确认并关闭窗口" },
	{ on = "<Enter>", run = "close --submit", desc = "确认并提交" },

	{ on = "n", run = "close",          desc = "选择否，取消确认" },
	{ on = "y", run = "close --submit", desc = "选择是，确认并提交" },

	{ on = "k", run = "arrow prev", desc = "光标上移一行" },
	{ on = "j", run = "arrow next", desc = "光标下移一行" },

	{ on = "<Up>",   run = "arrow prev", desc = "光标上移一行" },
	{ on = "<Down>", run = "arrow next", desc = "光标下移一行" },

	# 帮助
	{ on = "~",    run = "help", desc = "打开帮助文档" },
	{ on = "<F1>", run = "help", desc = "打开帮助文档" },
]

[cmp]

keymap = [
	{ on = "<C-c>",   run = "close",                                      desc = "取消补全，关闭菜单" },
	{ on = "<Tab>",   run = "close --submit",                             desc = "确认补全选项" },
	{ on = "<Enter>", run = [ "close --submit", "input:close --submit" ], desc = "确认补全并提交输入内容" },

	{ on = "<A-k>", run = "arrow prev", desc = "光标上移，选择上一个补全项" },
	{ on = "<A-j>", run = "arrow next", desc = "光标下移，选择下一个补全项" },

	{ on = "<Up>",   run = "arrow prev", desc = "光标上移，选择上一个补全项" },
	{ on = "<Down>", run = "arrow next", desc = "光标下移，选择下一个补全项" },

	{ on = "<C-p>", run = "arrow prev", desc = "光标上移，选择上一个补全项" },
	{ on = "<C-n>", run = "arrow next", desc = "光标下移，选择下一个补全项" },

	# 帮助
	{ on = "~",    run = "help", desc = "打开帮助文档" },
	{ on = "<F1>", run = "help", desc = "打开帮助文档" },
]

[help]

keymap = [
	{ on = "<Esc>", run = "escape", desc = "清除过滤器或关闭帮助界面" },
	{ on = "<C-[>", run = "escape", desc = "清除过滤器或关闭帮助界面" },
	{ on = "<C-c>", run = "close",  desc = "关闭帮助界面" },

	# 导航
	{ on = "k", run = "arrow prev", desc = "向上移动一行" },
	{ on = "j", run = "arrow next", desc = "向下移动一行" },

	{ on = "<Up>",   run = "arrow prev", desc = "向上移动一行" },
	{ on = "<Down>", run = "arrow next", desc = "向下移动一行" },

	# 过滤
	{ on = "f", run = "filter", desc = "过滤帮助条目" },
]
